### ISSUE TITLE
HashMap type in rust is getting converted to Record instead of Map 

### ISSUE THREAD

**Issue by KusumaShekarN** [dbeckwith/rust-typescript-type-def#11]
eg:
pub input: HashMap<String, String> 

is getting converted to
input: Record<string, string>;

instead of 
input: Map<string, string>;

**Comment by dbeckwith** [comment]
Yes this is intentional. When a Rust `HashMap` is serialized to JSON, the result is a plain JavaScript object, which in Typescript is described using `Record`. A [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) in JavaScript/Typescript is a class object for a map datastructure, which functions similarly to Rust's `HashMap`, but is not part of JSON. This library only deals with defining types for the JSON serialization of Rust values according to `serde-json`.
