### ISSUE TITLE
How to make this work with Chrono

### ISSUE THREAD

**Issue by lingfei1999** [dbeckwith/rust-typescript-type-def#19]
Hi, firstly, thanks for creating this useful library. While using it, I have problem with TypeDef and Chrono. This is what I have: 

```
pub struct Test { 
  pub created_date: NaiveDateTime
}
```

I do have the lib chrono with features serde, and it prints out to string json just fine, but doesn't seem to work with derive TypeDef.

**Comment by dbeckwith** [comment]
Every field's type needs to implement the `TypeDef` trait in order for the derive to work, which `NaiveDateTime` doesn't because it comes from a different library. In that case, you can use the [`type_of`](https://docs.rs/typescript-type-def/latest/typescript_type_def/trait.TypeDef.html#foreign-types) option here, like so:
```rust
#[derive(TypeDef)]
pub struct Test { 
  #[type_def(type_of = "String")]
  pub created_date: NaiveDateTime
}
```
This tells the derive to generate types for that field that match the types of `String`, which seems to be appropriate here since `NaiveDateTime` serializes to a string.
