### ISSUE TITLE
Improve formatting of output

### ISSUE THREAD

**Issue by holly-hacker** [dbeckwith/rust-typescript-type-def#23]
When creating typescript definitions for large structs, all structs of the field are on the same line and there is no indentation in the entire file. This makes it hard to manually inspect the file while developing on the TypeScript side. It would be nice if there was some form of pretty-printing to ease this issue.

It's possibly to do this after the code was generated using a crate like [`dprint-plugin-typescript`](https://lib.rs/crates/dprint-plugin-typescript) but this bloated the release build of my binary from 670kb to 5.1mb and compile time increased by a similar amount.

For clarity, this is a file that was generated for me:
```ts
// AUTO-GENERATED by typescript-type-def

export default types;
export namespace types{
export type I32=number;
export type U32=number;
export type F32=number;
export type ItemData={"name":(string|null);"temp_name":(string|null);"temp_end_event":(string|null);"sort":types.I32;"img_no":types.I32;"price":types.U32;"lv":types.U32;"element":(types.U32|null);"element_value":(types.U32|null);"elem_fire":(types.I32|null);"elem_ice":(types.I32|null);"elem_thunder":(types.I32|null);"elem_air":(types.I32|null);"pc":(types.I32)[];"hp":(types.I32|null);"atk":(types.I32|null);"def":(types.I32|null);"spd":(types.I32|null);"w_hp":(types.F32|null);"w_mp":(types.F32|null);"w_atk":(types.F32|null);"w_def":(types.F32|null);"w_spd":(types.F32|null);"dlc":(string)[];"use_tag":string;"kind_tag":string;"bme":(string|null);"bmee":(string|null);"cat":(string)[];};
export type Data={"item_data":(types.ItemData)[];};
}
```

**Comment by dbeckwith** [comment]
Are you generating your TS types in a Cargo build script? If so, pulling in formatter dependencies like the one you mentioned shouldn't impact the size of your binary because these are only used at build time (as long as you put them in the `build-dependencies` section in Cargo.toml). Any compile time shouldn't be affected too much since Cargo should only need to build those crates once (assuming you're in an environment where you can cache builds). I typically use a NodeJS installation of Prettier to format the types generated by this library, since I usually have it installed anyway for TS development in the same project.

With that said, I suppose I could make some adjustments to the output to at least put each field on its own line to make it a bit more readable, but I don't want to add too much complexity to this library around simplifying (e.g. removing unneeded parentheses) and prettifying the output.

**Comment by dbeckwith** [comment]
Here's an example from the tests in this library of what this might look like with extra line breaks:

```typescript
/// before
export type Test10=({"type":"A";"value":(types.Parent&{"a":string;"b":types.Usize;});}|{"type":"B";"value":{"A":types.Test4;"B":types.Test5;"C":types.Test6;"D":types.Test7;"E":types.TEST_8;"F":(types.Test9|null);"G":null;};}|{"type":"C";"value":types.Parent;}|{"type":"D";}|{"type":"E";"value":{};}|{"type":"F";"value":[];});

/// after
export type Test10=({
"type":"A";
"value":(types.Parent&
{
"a":string;
"b":types.Usize;
});
}|
{
"type":"B";
"value":{
"A":types.Test4;
"B":types.Test5;
"C":types.Test6;
"D":types.Test7;
"E":types.TEST_8;
"F":(types.Test9|
null);
"G":null;
};
}|
{
"type":"C";
"value":types.Parent;
}|
{
"type":"D";
}|
{
"type":"E";
"value":{
};
}|
{
"type":"F";
"value":[];
});
```

I suppose it's a bit better, but as I said, generating fully formatted output can be quite complex and isn't something I want to add to this library; you should probably always be using some other tool to format the output.

**Comment by holly-hacker** [comment]
The way the Debug trait does it, to my knowledge, is by passing in an indentation variable that gets incremented on every child call so that shouldn't be too bad unless this library has some fairly complex output. I could give this a try if I have some free time.
