### ISSUE TITLE
Enums are exported as union types instead of enums

### ISSUE THREAD

**Issue by nappa85** [dbeckwith/rust-typescript-type-def#27]
This code
```rust
#[derive(TypeDef)]
pub enum Foo {
    Bar0,
    Bar1,
    Bar2,
    Bar3,
    Bar4,
}
```

is exporting this type definition
```typescript
export type Foo = ("Bar0" | "Bar1" | "Bar2" | "Bar3" | "Bar4");
```

instead it should export something like this
```typescript
export enum Foo { Bar0 = "Bar0", Bar1 = "Bar1", Bar2 = "Bar2", Bar3 = "Bar3", Bar4 = "Bar4" };
```

**Comment by dbeckwith** [comment]
This is intentional. The explicitly stated goal of this library is to generate Typescript types which describe how `serde_json` serializes Rust values. A Typescript `enum` is not just a type, it's also a value, so it goes a bit beyond that scope. Also, a Typescript `enum` can only describe primitive values, and couldn't be used to represent a Rust enum like `pub enum Foo { Bar0 { x: u32 }, Bar1 }`.

**Comment by nappa85** [comment]
Makes sense, thanks for the reply
