### ISSUE TITLE
How to define TypeDef for types like `uuid::Uuid`?

### ISSUE THREAD

**Issue by greatcat19** [dbeckwith/rust-typescript-type-def#28]
Hello!

I tried to do something like this:

```rs
impl TypeDef for Uuid {
    const INFO: TypeInfo = TypeInfo::Native(NativeTypeInfo {
        r#ref: TypeExpr::ident(Ident("string")),
    });
}
```

But it shows:
```
`Uuid` is not defined in the current craterustc[E0117](https://doc.rust-lang.org/error-index.html#E0117)
```

**Comment by dbeckwith** [comment]
As the Rust error code is indicating, you are running into a common constraint in Rust called the "orphan rule". You can't implement a foreign trait for a foreign type, because there's nothing preventing a different crate from doing the same thing and defining a conflicting implementation.

A common way to get around this is to create a local "newtype" wrapper around the type and use this instead. This is the approach I take in most of my projects, as it gives you a lot of control over other aspects of your type as well.
```rust
#[derive(Debug, Serialize, Deserialize)]
pub struct MyId(pub uuid::Uuid);

impl TypeDef for MyId {
    const INFO: TypeInfo = TypeInfo::Native(NativeTypeInfo {
        r#ref: TypeExpr::ident(Ident("string")),
    });
}
```

Another approach you can use is to tell the `TypeDef` macro to use a different type for the Typescript type wherever you mention `Uuid`:
```rust
#[derive(Serialize, Deserialize, TypeDef)]
pub struct MyStruct {
  #[type_def(type_of = "String")]
  pub id: Uuid;
  pub foo: usize;
}
```

You can also combine the two if you want to use a newtype but don't want to implement `TypeDef` manually:
```rust
#[derive(Debug, Serialize, Deserialize, TypeDef)]
pub struct MyId(#[type_def(type_of = "String")] pub uuid::Uuid);
```

**Comment by greatcat19** [comment]
Thank you so much, @dbeckwith !
The second approach is exactly what I've been looking for!
